### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by DevMaxiss** [DevMaxiss/Term-Project#1]
Presentation:
- [x] Background.
- [x] Game Environment (aka Canvas).
- [x] Scoreboard.
- [x] Instructions / Game rules.

User Interface:
- [x] Reset button.

Game Elements needed to be implemented:
- [x] Paddles and paddle controls.
- [x] Ball and ball physics.
- [x] Scoring and winning system.
- [x] Game reset system.

Optionals:
- [ ] Character select.
- [x] Sounds (?)
